from aiogram.utils.markdown import hbold


localization = {
    "uz": {
        "welcome_bot": "Salom ",
        "choose_direction": "Yo'nalishni tanlang:",
        "choose_lang": "Bot tilini tanlang:",
        "start_order_btn": "🛒 Buyurtmani boshlang",
        "events_btn": "🎉 Yordam",
        "info_btn": "ℹ️ Ma'lumot",
        "my_orders_btn": "📖 Mening buyurtmalarim",
        "settings_btn": "⚙️ Sozlamalar",
        "send_contact_text": "OK, endi bizga kontakt yuboring!",
        "send_contact_btn": "📞 Kontaktni yuboring",
        "back_to_main_btn": "⬅️ Asosiy menyu",
        "interact_menu_btn": "Interaktiv menyu",
        "interact_menu_text": "Interaktiv Menyuda buyurtma berishga harakat qiling 🤖",
        "pickup_text": "Hozirda u ishlab chiqilmoqda. 🙃",
        "booking_text": f"Siz turni tanladingiz: {hbold('bron qilish')}",
        "choose_type_order": "Buyurtma turini tanlang.",
        "choose_category": "Toifani tanlang:",
        "choose_dish": "Taomni tanlang:",
        "booking_btn": "🍽️ Jadvalni bron qilish",
        "pickup_btn": "🚶 Olib ketish",
        "back_btn": "⬅️ Orqaga",
        "into_cart_btn": "🛒 Savatga",
        "cart_btn_in_menu": "🛒 Savat",
        "plus_quantity_text": "Soni ko'paytirildi",
        "minus_quantity_text": "Miqdori kamaytirildi",
        "empty_cart": "Kechirasiz, lekin savatingiz bo'sh 😅",
        "create_order_btn": "✅ Buyurtma",
        "select_time": "Stolni bron qilish uchun sizga qulay vaqtni belgilang:",
        "near_soon_btn": "✅ Tez orada",
        "set_time_btn": "🕛 Vaqtni belgilang",
        "to_review_btn": "📝 Fikr qoldiring",
        "pay_order": "💳 To'lash",
        "select_table_text": "OK, endi joyni tanlang.",
        "set_time_text": "Jadvalni bron qilish uchun vaqtni quyidagicha yuboring ##:##",
        "error_format_time": "Format to'g'ri, lekin vaqt to'g'ri emas! Yana takrorlang.",
        "error_text_time": "Vaqtni yozishda xato! Yana takrorlang.",
        "set_quantity_people": "Ajoyib, endi odamlarga qo'ng'iroq qiling:",
        "succes_create_order": "Ajoyib, dastur yaratildi, menejerdan tasdiqlashni kuting. 😊",
        "error_wrong_quantity": "Xato noto'g'ri qo'ng'iroq qilingan! Yana takrorlang.",
        "error_format_quantity": "Xato qo'ng'iroq emas edi! Yana takrorlang.",
        "choose_type_order": "Zo'r, endi to'lov turini tanlang:",
        "succes_payment_order": "Sizning buyurtmangiz davom etmoqda! ☺️\nBuyurtma holati yangilandi.\nJoriy buyurtmalarni 'mening buyurtmalarim' da ko'rishingiz mumkin",
        "my_last_three_orders": "Sizning oxirgi 3 buyurtmangiz:",
        "empty_orders": "Sizda bitta buyurtma yo'q. 😅",
        "choose_action": hbold('Amalni tanlang:'),
        "change_language_btn": "🇺🇿 Tilni o'zgartiring",
        "change_phone": "📞 Raqamni o'zgartiring",
        "choose_language_settings": hbold('Tilni tanlang:'),
        "succes_changed_language": "Til muvaffaqiyatli o'zgartirildi! 😀",
        "change_phone_text": hbold('Kiritish uchun raqamni 998########## shaklida kiriting:'),
        "succes_changed_phone": "Raqam muvaffaqiyatli o'zgartirildi! 😉",
        "events": hbold('Yordam'),
        "error_form_phone": "Raqamni kiritishda xato!"
    },
    "ru": {
        "welcome_bot": "Зравствуйте ",
        "choose_direction": "Выберите направление:",
        "choose_lang": "Выберите язык бота:",
        "start_order_btn": "🛒 Начать заказ",
        "events_btn": "🎉 Акции",
        "info_btn": "ℹ️ Информация",
        "my_orders_btn": "📖 Мои заказы",
        "settings_btn": "⚙️ Настройки",
        "send_contact_text": "Хорошо, теперь отправьте нам контакт!",
        "send_contact_btn": "📞 Отправить контакт",
        "back_to_main_btn": "⬅️ Главное меню",
        "interact_menu_btn": "Интерактивное меню",
        "interact_menu_text": "Попробуйте заказать в интерактивном меню 🤖",        
        "pickup_text": "В данный момент находиться в разработке. 🙃",     
        "booking_text": f"Вы выбрали тип: {hbold('Бронирование')}",
        "choose_type_order": "Выберите тип заказа.",
        "choose_category": "Выберите категорию:",        
        "choose_dish": "Выберите блюдо:",           
        "booking_btn": "🍽️ Бронирование стола",
        "pickup_btn": "🚶 Самовывоз",        
        "back_btn": "⬅️ Назад",
        "into_cart_btn": "🛒 В корзину",   
        "cart_btn_in_menu": "🛒 Корзина",
        "plus_quantity_text": "Колличество увеличено",       
        "minus_quantity_text": "Колличество увеличено",  
        "empty_cart": "Извините, но ваша корзинка пуста 😅",
        "create_order_btn": "✅ Заказать", 
        "select_time": "Укажите удобное для вас время для брони столика:", 
        "near_soon_btn": "✅ Ближайшее время",
        "set_time_btn": "🕛 Указать время",
        "to_review_btn": "📝 Оставить отзыв",
        "pay_order": "💳 Оплатить",
        "select_table_text": "Хорошо, теперь выберите место.",
        "set_time_text": "Для брони столика отправьте время в виде ##:##",
        "error_format_time": "Формат допустимый, но время не правильное! Повторите еще раз.",
        "error_text_time": "Ошибка при написании времени! Повторите еще раз.",
        "set_quantity_people": "Отлично, теперь введите колл-во людей:",
        "succes_create_order": "Отлично, заявка создана, ждите одобрение от мененджера. 😊",
        "error_wrong_quantity": "Ошибка указано неправильное колл-во! Повторите еще раз.",
        "error_format_quantity": "Ошибка указано было не колл-во! Повторите еще раз.",
        "choose_type_order": "Отлично, теперь выберите тип оплаты:",
        "succes_payment_order": "Ваш заказ в процессе! ☺️\nСтатус заказа обновлен.\nТекущие заказы вы можете посмотреть в 'Мои заказы'",
        "my_last_three_orders": "Ваши последние 3 заказа:",
        "empty_orders": "У вас нету ни одного заказа. 😅",
        "choose_action": hbold('Выберите действие:'),
        "change_language_btn": "🇺🇿 Сменить язык",
        "change_phone": "📞 Сменить номер",
        "choose_language_settings": hbold('Выберите язык:'),
        "succes_changed_language": "Язык успешно изменен!😀",
        "change_phone_text": hbold('Введите номер в виде 998##########:'),
        "succes_changed_phone": "Номер успешно изменен!😉",
        "events": hbold('Акции'),
        "error_form_phone": "Ошибка при вводе номера!"
    },
}