version: '3.8'

services:
 api: 
    build:
      context: .
      dockerfile: api/Dockerfile
    command: sh -c "python3 api/manage.py makemigrations && python3 api/manage.py migrate --noinput && python3 api/manage.py collectstatic --noinput"
    environment:
      - DATABASE_HOST=database
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env
 bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: python bot/main.py
    depends_on:
      - api 
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    environment:
      - URL=http://api:8000/
 db:
    image: postgres:13
    environment:
      - POSTGRES_DB=web_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18960707
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
      
 nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/www/static/:/var/www/static/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api

volumes:
 postgres_data: