# Generated by Django 5.0.1 on 2024-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.CharField(default='Свободен', verbose_name='Статус'),
        ),
    ]
