# Generated by Django 5.0.1 on 2024-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название категории на русском')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Название категории на узбекском')),
            ],
            options={
                'verbose_name': 'Категория Блюд',
                'verbose_name_plural': 'Категории Блюд',
            },
        ),
    ]
