# Generated by Django 5.0.1 on 2024-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.AddField(
            model_name='categories',
            name='title_ru',
            field=models.CharField(default=5, max_length=100, verbose_name='Название категории RU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='title_uz',
            field=models.CharField(default=5, max_length=100, verbose_name='Название категории UZ'),
            preserve_default=False,
        ),
    ]
