# Generated by Django 5.0.1 on 2024-01-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_alter_categories_options_remove_categories_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subategories',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Categories.categories', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
