# Generated by Django 5.0.1 on 2024-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_subategories_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subategories',
        ),
    ]
