# Generated by Django 5.0.1 on 2024-01-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=155, verbose_name='Название блюда на русском')),
                ('title_uz', models.CharField(max_length=155, verbose_name='Название блюда на узбекском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Изображение')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_uz', models.TextField(verbose_name='Описание на узбекском')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Categories.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюдо',
            },
        ),
    ]
