# Generated by Django 5.0.1 on 2024-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='jovy_dish_pk',
            field=models.IntegerField(default=2, verbose_name='Айди блюда в Jovy'),
            preserve_default=False,
        ),
    ]
