# Generated by Django 5.0.1 on 2024-01-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Блюд', 'verbose_name_plural': 'Блюдо'},
        ),
    ]
