# Generated by Django 5.0.1 on 2024-03-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishes_jovy_dish_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='jovy_dish_pk',
        ),
    ]
