# Generated by Django 5.0.1 on 2024-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dishes_jovy_dish_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='title',
        ),
        migrations.AddField(
            model_name='dishes',
            name='description_ru',
            field=models.TextField(default=5, verbose_name='Описание RU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='description_uz',
            field=models.TextField(default=54, verbose_name='Описание UZ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='title_ru',
            field=models.CharField(default=54, max_length=155, verbose_name='Название блюда RU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='title_uz',
            field=models.CharField(default=54, max_length=155, verbose_name='Название блюда UZ'),
            preserve_default=False,
        ),
    ]
