# Generated by Django 5.0.1 on 2024-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0003_alter_dishes_options_alter_dishes_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='description_ru',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='title_uz',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(default=6, upload_to='dishes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
