# Generated by Django 5.0.1 on 2024-05-18 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(blank=True, null=True, verbose_name='Тип')),
                ('place', models.CharField(blank=True, default='-', null=True, verbose_name='Место')),
                ('people_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во людей')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('datetime_selected', models.TimeField(blank=True, null=True, verbose_name='Указанное время')),
                ('status', models.CharField(blank=True, null=True, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Общая стоимость')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Общее кол-во')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказанное блюдо',
                'verbose_name_plural': 'Заказанные блюда',
            },
        ),
    ]