# Generated by Django 5.0.1 on 2024-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='people_quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во людей'),
        ),
    ]
