# Generated by Django 5.0.1 on 2024-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_table_dishorder_order_orders_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='table',
        ),
    ]
