# Generated by Django 5.0.1 on 2024-04-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('places', '0002_places_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='places.places', verbose_name='Место'),
            preserve_default=False,
        ),
    ]
