# Generated by Django 5.0.1 on 2024-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='people_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во людей'),
        ),
    ]
