# Generated by Django 5.0.1 on 2024-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Принят', 'Принят'), ('Закончен', 'Закончен')], default=('Ожидание', 'Ожидание')),
            preserve_default=False,
        ),
    ]
