# Generated by Django 5.0.1 on 2024-05-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_people_quantity'),
        ('places', '0002_places_is_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='place',
            field=models.ForeignKey(blank=True, default='Нету', null=True, on_delete=django.db.models.deletion.CASCADE, to='places.places', verbose_name='Место'),
        ),
    ]
