# Generated by Django 5.0.1 on 2024-04-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_status'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tables', verbose_name='Номер стола'),
        ),
    ]
