# Generated by Django 5.0.1 on 2024-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_type_order_alter_orders_people_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='people_quantity',
            field=models.IntegerField(blank=True, default='-', null=True, verbose_name='Кол-во людей'),
        ),
    ]
