# Generated by Django 5.0.1 on 2024-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type_order',
            field=models.CharField(blank=True, null=True, verbose_name='Тип'),
        ),
    ]
