# Generated by Django 5.0.1 on 2024-04-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_remove_dishes_description_remove_dishes_title_and_more'),
        ('orders', '0009_orders_dish_delete_dishesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_quantity',
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Общее кол-во')),
                ('dish', models.ManyToManyField(to='dishes.dishes', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказанное блюдо',
                'verbose_name_plural': 'Заказанные блюда',
            },
        ),
    ]
