# Generated by Django 5.0.1 on 2024-04-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_remove_dishes_description_remove_dishes_title_and_more'),
        ('orders', '0010_remove_orders_dish_remove_orders_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishorder',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishorder',
            name='dish',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes', verbose_name='Блюдо'),
            preserve_default=False,
        ),
    ]
