# Generated by Django 5.0.1 on 2024-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_dishorder_dish_dishorder_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='dishorder',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее кол-во'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='people_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во людей'),
        ),
    ]
