# Generated by Django 5.0.1 on 2024-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_latitude_orders_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='datetime_selected',
            field=models.TimeField(blank=True, null=True, verbose_name='Указанное время'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='latitude',
            field=models.CharField(blank=True, default='-', null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='longitude',
            field=models.CharField(blank=True, default='-', null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
