# Generated by Django 5.0.1 on 2024-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='is_view',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
