# Generated by Django 5.0.1 on 2024-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотокарточка')),
            ],
            options={
                'verbose_name': 'Эвент',
                'verbose_name_plural': 'Эвенты',
            },
        ),
    ]
