# Generated by Django 5.0.1 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='text',
            field=models.TextField(default=2, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
