# Generated by Django 5.0.1 on 2024-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default=44, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default=55, verbose_name='Название эвента'),
            preserve_default=False,
        ),
    ]
