# Generated by Django 5.0.1 on 2024-03-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='text',
            new_name='description',
        ),
    ]
