# Generated by Django 5.0.1 on 2024-04-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_description_events_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='description_RU',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='description_UZ',
            new_name='description_uz',
        ),
    ]
